//create new instance of class means crating new object
//class variablename = NEW class();
primitiveDataTypeDemo pt = new primitiveDataTypeDemo();
pt.printBasicDataType();
pt.printNewDate();
pt.printNewTime();
pt.printNewDateTime();

DatetimeMethodsDemo demo = new DatetimeMethodsDemo();
demo.calculateAgeInMonths();
demo.calculateAgeInDays();
demo.printSubscriptionEndDate();
demo.printOfferEndDateTime();